function createfigure(XData1, YData1, YData2,dd)
%CREATEFIGURE(XDATA1,YDATA1,YDATA2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
Xm = dd(1,1);
XM = dd(2,1);
Ym = min(YData1);
YM = max(YData1);
%  Auto-generated by MATLAB on 23-Aug-2013 13:44:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YColor',[1 0 0],'XColor',[1 0 0],'visible','off');
 fill([Xm Xm XM XM],[Ym YM YM Ym],'b','FaceAlpha',0.1, 'EdgeColor',[1 1 1],'DisplayName','最大回撤区')

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',2,'LineStyle','--',...
    'Color',[1 0 0],...
    'DisplayName','累计收益');
title('螺纹钢走势跟踪');
% Create axes
axes2 = axes('Parent',figure1,'YAxisLocation','right','XAxisLocation','bottom',...
    'Color','none');
 ylim(axes1,[Ym YM]);

grid(axes2,'on');
hold(axes2,'all');


% Create line
line(XData1,YData2,'Parent',axes2,'Marker','+','LineWidth',1,'DisplayName','螺纹钢走势');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 0 0],'Orientation','horizontal','YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'Location','Best',...
    'FontSize',8);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'EdgeColor',[0 0 1],'Orientation','horizontal','YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'Location','Best',...
    'FontSize',8,...
    'Color',[1 1 1]);


