function Signalforcast(Y1, Y2)
%CREATEFIGURE1(Y1,Y2)
%  Y1:  stem y
%  Y2:  stairs y

%  Auto-generated by MATLAB on 24-Aug-2013 11:21:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-2 2]);
box(axes1,'on');
hold(axes1,'all');

% Create stem
stem(Y1,'MarkerFaceColor',[1 0 0],'Marker','pentagram','Color',[0 0 1],...
    'Parent',axes1,...
    'DisplayName','预测信号');

% Create stairs
stairs(Y2,'Color',[0 0.5 0],'Parent',axes1,'DisplayName','真实信号');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.694399569197631 0.78454231433506 0.197092084006462 0.10880829015544]);

